name: Publish Node16 Image

on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: Setup bazel
        uses: jwlawson/actions-setup-bazel@v1
        with:
          bazel-version: '5.1.1'
      - name: Use bazel
        run: bazel --version
        
      - name: Setup pack
        uses: buildpacks/github-actions/setup-pack@v4.1.0
        
      - name: Setup container-structure-test
        run: curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && chmod +x container-structure-test-linux-amd64 && mkdir -p $HOME/bin && export PATH=$PATH:$HOME/bin && mv container-structure-test-linux-amd64 $HOME/bin/container-structure-test
        
      - name: Build node16 stack
        run: bazel run //builders/node16/stack:build
        
      - name: Build node16 builder
        run: bazel build //builders/node16:builder.image
        
#       - name: Test node16
#         run: bazel test //builders/node16/acceptance/...
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Tag and push the image
        run: |
          docker tag of/node16 openfunction/builder-node:v2-16.15
          docker push openfunction/builder-node:v2-16.15
          docker tag of/node16 openfunction/builder-node:latest
          docker push openfunction/builder-node:latest
        
      
